hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("walker --gapplication-service")
    hl.exec_cmd("systemctl --user restart elephant")
    hl.exec_cmd("ags run ~/.config/ags")
end)
