---
omarchy_wallpapers_source: "{{ dotfiles_root }}/config/user/omarchy/wallpapers"
omarchy_wallpapers_target: "{{ dotfiles_home }}/.config/omarchy/backgrounds/Catppuccin"
omarchy_wallpapers_state_link: "{{ dotfiles_home }}/.local/state/omarchy/current/background"
omarchy_wallpapers_default: elf-prison.jpg
omarchy_wallpapers_systemd_user_dir: "{{ dotfiles_home }}/.config/systemd/user"
omarchy_wallpapers_rotation_service: dotfiles-omarchy-wallpaper-rotation.service
omarchy_wallpapers_rotation_timer: dotfiles-omarchy-wallpaper-rotation.timer
omarchy_wallpapers_next_command: /usr/share/omarchy/bin/omarchy-theme-bg-next
