---
hyprland_monitors:
  - output: DP-3
    mode: 1920x1080@60
    position: '2560x0'
    scale: 1
    disabled: false
  - output: HDMI-A-1
    mode: 2560x1080@60
    position: '0x0'
    scale: 1
  - output: ''
    mode: preferred
    position: auto
    scale: auto
