name = "monitors"
name_pretty = "Monitores"
icon = "video-display"
fixed_order = true

[[entries]]
text = "Desativar Segunda Tela"
icon = "display-disable"
actions = { "run" = "hyprctl keyword monitor DP-3,disable" }

[[entries]]
text = "Ativar Segunda Tela"
icon = "display-enable"
actions = { "run" = "hyprctl keyword monitor DP-3,preferred,auto,1" }
