---
terminal_kitty_packages: []
terminal_kitty_target: "{{ dotfiles_home }}/.config/kitty"
terminal_kitty_entries:
  - name: "One Dark.conf"
    expected_source: "{{ dotfiles_root }}/config/user/kitty/One Dark.conf"
    legacy_sources: []
  - name: current-theme.conf
    expected_source: "{{ dotfiles_root }}/config/user/kitty/current-theme.conf"
    legacy_sources: []
  - name: kitty.conf
    expected_source: "{{ dotfiles_root }}/config/user/kitty/kitty.conf"
    legacy_sources: []
  - name: kitty.conf.bak
    expected_source: "{{ dotfiles_root }}/config/user/kitty/kitty.conf.bak"
    legacy_sources: []
